import './globals.css'
import { Inter } from 'next/font/google'
import 'draft-js/dist/Draft.css';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        
      <body className={inter.className}>{children}</body>
      <Script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp" />
    </html>
  )
}
